### ISSUE TITLE
direct people to turn on issues?

### ISSUE THREAD

**Issue by ajschumacher** [thisismetis/dsp#1]
Issues are off by default for forks, but you can turn them on in settings.

@laumontemayor I'm a little bit loathe to update the repo now that people have started forking it, but at least for the next cohort we could add to the repo setup directions to turn on issues for students' forks.

@reshama what do you think of the possibility of using github issues for feedback on pre-work? Is that worth trying? It might be a place where we would rather give feedback in private; I'm not sure.

**Comment by ajschumacher** [comment]
Hmm I'm not sure this is a good idea. I'll leave it open for a while.

**Comment by laumontemayor** [comment]
@reshama @ajschumacher I kinda of want to reopen this idea. :grimacing: 
 But maybe it's not the best timing. We can reopen.

**Comment by ajschumacher** [comment]
Talking to @reshama and she wants to reopen :smile:

**Comment by reshama** [comment]
@laumontemayor we can open issues.  7 students have already forked, but it may be helpful for the others.

**Comment by laumontemayor** [comment]
Release the hounds :dog:
