### ISSUE TITLE
Incorporate additional resources

### ISSUE THREAD

**Issue by klq** [thisismetis/dsp#44]
@reshama @aramnath 

We have some additional resources links in the dscurriculum/00-prework directory that are not in the dsp repo 08-resources section. We need to actually incorporate these resources to the official dsp repo.

https://github.com/thisismetis/dscurriculum/blob/master/00-prework/more_prework_resources.md

**Comment by reshama** [comment]
hi @klq 
Which ones, specifically? Some of those links are notes that I have been taking.  They are not meant to be a 1:1 match with dsp.

**Comment by klq** [comment]
@reshama 
There are several resources in in here that was not in the prework repo, eg. visualizing hyperplanes, Khan academy linear algebra course, dot product, cosine similarity (cosine of vectors) etc. 

My original understanding was dscurriculum is something that will keep evolving whereas dsp gets different for each iteration.  So the changes in dscurriculum would eventually be incorporated in the dsp. Otherwise, the students won't see dscurriculum anyways, why put resource list in here? I might be wrong, so please do correct me.

-klq

**Comment by reshama** [comment]
@klq 
https://github.com/thisismetis/dsp/blob/master/06-linear_algebra.md

**Comment by klq** [comment]
Hey @reshama 
I'm not reopening this issue, but I do think we need to continue this discussion. 

Several items in the list is just kind of orphaned:
[Functions - brief overview with 6 exercises and solutions](https://erlerobotics.gitbooks.io/erle-robotics-learning-python-gitbook-free/content/functions/README.html)
[Khan Academy Linear Algebra](https://www.khanacademy.org/math/linear-algebra)
[Kardi’s Interactive Linear Algebra Tutorial] (http://people.revoledu.com/kardi/tutorial/LinearAlgebra/index.html)

Do we want to recommend these resources as additional reading for prework?   
If they are not important, maybe take it off completely, but if they are, then we should incorporate these in the dsp repo for students to see. 
-klq
